services:
  debrid:
    build: .
    ports:
      - "5001:5001"
    volumes:
      - ./public:/app/public
      - ./views:/app/views
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    restart: unless-stopped
    container_name: bakaworld
